from elasticsearch import Elasticsearch
# from google.oauth2 import service_account
import pandas as pd
import json
import re





# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "pass"

# Found in the 'Manage Deployment' page
CLOUD_ID = "My_deployment"

# Create the client instance
es = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(es.info())
index_name = 'search-layoff'

# delete all documents from the index
es.delete_by_query(index=index_name, body={"query": {"match_all": {}}})