from elasticsearch import Elasticsearch
# from google.oauth2 import service_account
import pandas as pd
import json
import re





# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "pass"

# Found in the 'Manage Deployment' page
CLOUD_ID = "My_deployment"

# Create the client instance
es = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(es.info())
# index_name = 'search-layoff'

# delete all documents from the index
# es.delete_by_query(index=index_name, body={"query": {"match_all": {}}})


layoff_df = pd.read_csv('./layoff_report.csv')
# print(layoff_df.head())
pattern = re.compile(r"^(\d*\w+)", re.IGNORECASE)
# # Convert DataFrame rows to JSON and index them in Elasticsearch
for index, row in layoff_df.iterrows():
    # convert the row to a dictionary and then to a JSON string
    layoff_dict = row.to_dict()
    layoff_dict['Company_First_Word'] = pattern.match(layoff_dict['Company']).group(1)
    layoff_json = json.dumps(layoff_dict)

    # Create the index if it doesn't exist
    
    if not es.indices.exists(index='search-layoff'):
        index_settings = {
            "mappings": {
                "properties": {
                    "Company_First_Word": {
                        "type": "keyword"
                    }
                }
            }
        }
        es.indices.create(index='search-layoff', body=index_settings)

    # index the JSON document into Elasticsearch
    res = es.index(index='search-layoff', body=layoff_json)
    print(res)

