from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "pass"

# Found in the 'Manage Deployment' page
CLOUD_ID = "My_deployment"

# Create the client instance
es = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

search_word = "microsoft"
query = {
    "query": {
        "match": {
            "Company_First_Word": {
                "query": search_word
            }
        }
    },
    "size": 100,
    "_source": {
        "excludes": ["Company_First_Word"]
    }
}

res = es.search(index="search-layoff", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_source"])
